### ISSUE TITLE
Microbundle error? No exported member

### ISSUE THREAD

**Issue by markojak** [albingroen/react-cmdk#1]
This looks awesome. Cloned the main branch to see if I could get it to work and after yarn install and then `yarn start` I'm getting this error

Can you help

```
(rpt2 plugin) Error: /Users/x/workspace/react-cmdk/src/index.tsx(5,10): semantic error TS2724: Module '"../node_modules/twind/twind"' has no exported member 'tw'. Did you mean 'TW'?
```

**Comment by markojak** [comment]
WorkAround
I added the following in my package.json -

```
"resolutions": {
    "**/typescript": "^4.1.5",
    "**/@typescript-eslint/eslint-plugin": "^4.15.1",
    "**/@typescript-eslint/parser": "^4.15.1"
  }
```

Then I ran the following
`yarn add --dev typescript@latest @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest`

**Comment by markojak** [comment]
In general would be good to be able to get a development environment up so that I can help contribute.

**Comment by albingroen** [comment]
Yeah I don't know. `microbundle-crl` is pretty flakey, and this should probably be redone with something else.

**Comment by albingroen** [comment]
@markojak The project is now re-architected and uses [tsdx](https://tsdx.io/) so it should be pretty seamless to get a local development environment up and running.
