### ISSUE TITLE
Dark Mode not controllable

### ISSUE THREAD

**Issue by OmegaHawkeye** [albingroen/react-cmdk#10]
Hello,

first of all great project but I got 1 small problem. 

I want to have  a  theme toggle but since you have `"darkMode": "media"` in your tailwind.config.js this isn't posible.

I wanted to ask if u could mby change it to some kind of env variable, since u obvioulsy can't access any kind of other app state and it won't make that much of a difference but for someone like me it would definitily help

**Comment by albingroen** [comment]
I can unfortunately only choose between auto dark mode or manual dark mode, so I will settle for auto dark mode for now.

**Comment by bjain3** [comment]
@albingroen Is there a way to override it or pass the mode. As I am not using tailwindcss. I am using mui and there is toggleSwitch for switching between dark and light mode. Light mode looks fine but dark mode doesn't  work.

Thanks.
