### ISSUE TITLE
Styling and dark mode

### ISSUE THREAD

**Issue by jpsear** [albingroen/react-cmdk#11]
Hey, thanks for the library. I've managed to get things working with my own data fairly quickly.

However, as far as I can tell, there is little to no way to hook into styling or even control dark mode — is this a limitation?

**Comment by albingroen** [comment]
Hi @jpsear, yes this is a limitation. If you want something that is stylable, check out this https://github.com/pacocoursey/cmdk

**Comment by jpsear** [comment]
Thanks for the response. That was indeed my preferred library, but it requires React 18, which is a fairly big upgrade for our commercial code base at the mo.

Thanks anyway 👍
