### ISSUE TITLE
How to style dark mode?

### ISSUE THREAD

**Issue by shouryan01** [albingroen/react-cmdk#23]
Hi there, I'm loving the library and how easy it is to use so far. I'm a little stuck on how to use and customize dark mode, can you help me out please?

**Comment by albingroen** [comment]
It's unfortunately not possible to style dark mode. I's automatic based on the users' computer appearance.

**Comment by shouryan01** [comment]
Gotcha, thanks. But the colors must be coming from somewhere right? Where is it getting the information to switch colors from black to white for the text?
