### ISSUE TITLE
Overly aggressive CSS selectors break components

### ISSUE THREAD

**Issue by imjared** [albingroen/react-cmdk#24]
Per the docs, an `icon` can take a `React.FC`. I'm trying to show a badge component that we use when we display projects. Normally this badge has its own styling included but it seems that it's blown away by some pretty aggressive rules:

<img src="https://user-images.githubusercontent.com/525011/214384204-a4e8644e-533d-40da-9d45-b47bc2460191.png">
<img src="https://user-images.githubusercontent.com/525011/214384258-0692dc63-f2b8-4144-9fd1-6e7ce08b4183.png" />

**Comment by albingroen** [comment]
This is kind of hard to do anything about since react-cmdk is built using Tailwind CSS for styling, which has quite an aggressive CSS reset built in.
