### ISSUE TITLE
Fuse.js for filtering

### ISSUE THREAD

**Issue by corysimmons** [albingroen/react-cmdk#25]
Instead of the custom filterItems fn, Fuse.js would be better. https://fusejs.io/

That is... if I know I want to find the term `Collapse Sidebars` I can usually just type something like `col si` into Fuse and it'll find the correct thing. Whereas with your custom filterItems fn, I'd have to type `collapse si` to get it over other `Collapse ______` terms.

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work
