### ISSUE TITLE
[Question]: Can I set my own Icons?

### ISSUE THREAD

**Issue by alinianitchii** [albingroen/react-cmdk#31]
Hi,

I would like to set my own Icons I'm using in my system.

Can adapt the library to accept other Icons?

Thank you

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/albingroen/react-cmdk/issues/31">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/albingroen/react-cmdk/issues/31/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/albingroen/react-cmdk/issues/31/pledge.svg">
</picture>
</a>

**Comment by Rahuletto** [comment]
Yes, but no at the same time. React CMDK supports React-Icons library and HeroIcons. So you can't use ur selected library but you can do it using `react-icons` package. If that package doesn't support your desired icons, you are screwed.

**Comment by ahmadassaf** [comment]
You can use whatever you want by overriding how the `<CommandPalette.ListItem>` is rendered.

For example; I want to show some social icons from `react-icons/pi` (can be any source or direct svg)

```js

import { PiLinkedinLogo } from 'react-icons/pi';

  const socialItems = filterItems(
    [
      {
        'heading': 'Contact Me',
        'id': 'contact',
        'items': [
          {
            'children': 'Linkedin',
            'closeOnSelect': false,
            'heroIcon': <PiLinkedinLogo/>,
            'id': 'linkedin',
            'onClick': () => {
              window.open('https://linkedin.com/in/.....', '_blank').focus();
            },
            'title': 'My Linkedin Profile'
          },
          .....
```

then when you are specifying your list:

```js
          <CommandPalette.List key={ list.id } heading={ list.heading }>
            {list.items.map(({ id, title, heroIcon, ...rest }) => (
              <CommandPalette.ListItem
                key={ id }
                index={ getItemIndex(socialItems, id) }
                { ...rest }
              >
                <div className='flex items-center w-full'>
                  {heroIcon}
                  <div className='mx-2 text-md'>{ title }</div>
                </div>
              </CommandPalette.ListItem>
            ))}
          </CommandPalette.List>
```

<img width="561" alt="image" src="https://github.com/albingroen/react-cmdk/assets/550726/5061df39-3196-45c5-a436-d37e96189464">

**Comment by nireld** [comment]
@ahmadassaf 
What is heroIcon?
by the way, my icon is ComponentType (I'm using React Admin)
how can I show this icon inside the model?

**Comment by albingroen** [comment]
Theres is not a way to change the icons unfortunately, and it will not be added in the near future.
