### ISSUE TITLE
[icon] Is there a way to change the icon?

### ISSUE THREAD

**Issue by jlia0** [albingroen/react-cmdk#32]
![image](https://user-images.githubusercontent.com/24471281/235310457-ecf20742-de07-4536-a158-e1aaa1f78609.png)
Is there a way to change the search icon to something else?

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/albingroen/react-cmdk/issues/32">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/albingroen/react-cmdk/issues/32/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/albingroen/react-cmdk/issues/32/pledge.svg">
</picture>
</a>

**Comment by jlia0** [comment]
@albingroen Thanks!

**Comment by albingroen** [comment]
Theres is not a way to change the icons unfortunately, and it will not be added in the near future.
