### ISSUE TITLE
Navigation to previous commands.

### ISSUE THREAD

**Issue by lucky-chap** [albingroen/react-cmdk#7]
Whenever a user navigates to a command with sub-commands, there's nothing to tell the user to press the Escape key to go back. I think showing some sort of help message can make the user navigate back from deep sub-commands, without trying to figure out which key to press. This is a huge problem on mobile phones

**Comment by albingroen** [comment]
Hi Quavo, I understand your problem and I will try to think of a good solution. For now though, maybe you can just render a back option, like this?
<img width="761" alt="image" src="https://user-images.githubusercontent.com/19674362/174002454-a7ce326b-945f-43f6-a916-da8e8a6440ba.png">

**Comment by dragonfire1119** [comment]
@albingroen Could you utilize delete or backspace, as raycast does?

**Comment by albingroen** [comment]
You can also use the `footer` property on the root component to show something like this.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/19674362/175784508-c927f720-0616-4130-af95-146ff61b4920.png">

**Comment by Semmu** [comment]
Just found this lib and wanted to say the same: going up a level via backspace would be really useful to implement.

**Comment by albingroen** [comment]
This PR adds support for hitting `Backspace` to move up a page (runs the `onEscape` if specified)
https://github.com/albingroen/react-cmdk/pull/8
